version: '3.8'

services:
  frankenphp:
    container_name: symfony_php
    build:
      context: ./docker/php
    ports:
      - "80:80"
      - "443:443"
      - "9003:9003" # для xdebug, если надо
    volumes:
      - ./app:/app
      - ./docker/php/Caddyfile:/etc/frankenphp/Caddyfile
    environment:
      APP_ENV: dev
    networks:
      - symfony
    depends_on:
      - db
      - elasticsearch
      - rabbitmq

  db:
    image: mysql:latest
    container_name: symfony-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_pass
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - symfony
    ports:
      - "3306:3306"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: symfony-elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
#    volumes:
#      - ./docker/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - symfony

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - symfony

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "472"
    ports:
      - "3000:3000"
    networks:
      - symfony
    volumes:
      - ./docker/grafana/:/var/lib/grafana

  jaeger:
    image: jaegertracing/all-in-one:1.47
    container_name: jaeger
    ports:
      - "16686:16686"   # UI
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
    networks:
      - symfony

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
    networks:
      - symfony

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # AMQP
      - "15672:15672"     # Web management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - symfony
networks:
  symfony:
    driver: bridge
