# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        task_index:
            persistence:
                driver: orm
                model: App\Domain\Entity\Task
                provider: ~
                listener: ~
                finder: ~
            properties:
                title: ~
                description: ~
                status: ~
            settings:
                number_of_shards: 1
                number_of_replicas: 0