# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        task_index:
            persistence:
                driver: orm
                model: App\Domain\Entity\Task
                provider: ~
                listener: ~
                finder: ~
            properties:
                title:
                    type: text
                    analyzer: edge_ngram_analyzer
                description:
                    type: text
                    analyzer: edge_ngram_analyzer
                status: ~
                priority:
                    type: integer
                createdAt:
                    type: date
                completedAt:
                    type: date
            settings:
                number_of_shards: 1
                number_of_replicas: 0
                analysis:
                    analyzer:
                        edge_ngram_analyzer:
                            tokenizer: edge_ngram_tokenizer
                            filter: [ lowercase ]
                    tokenizer:
                        edge_ngram_tokenizer:
                            type: edge_ngram
                            min_gram: 2
                            max_gram: 15
                            token_chars: [ letter, digit ]