framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
#            async:
#                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
#                options:
#                    use_notify: true
#                    check_delayed_interval: 60000
#                retry_strategy:
#                    max_retries: 3
#                    multiplier: 2
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                  exchange:
                    name: messages_exchange
                    type: direct
                  queues:
                    messages: ~
            failed: 'doctrine://default?queue_name=failed'
            fanout:
              dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
              options:
                exchange:
                  name: fanout_exchange
                  type: fanout
                queues:
                  my_queue_1: ~
                  my_queue_2: ~
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default:
                middleware:
                    - 'messenger.middleware.doctrine_transaction'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            App\Domain\Event\FanoutEvent: fanout


            # Route your messages to the transports
            # 'App\Message\YourMessage': async
